'use strict';
const SEED = [
  {id:'1042',name:'Maya Chen',initials:'MC',email:'maya.chen@example.com',subject:'My order was due yesterday',time:'9:42 AM',kind:'delay',label:'Delayed',tone:'orange',order:'NL-2084',product:'Everyday backpack',variant:'Forest / 1 item',total:'฿1,890.00',destination:'Chiang Mai, TH',ordered:'8 Sep 2026',promised:'12 Sep 2026',tracking:'PP-TH-082084',shipment:'Delivery delayed',shipmentNote:'Past the promised delivery date',progress:3,eta:'Not confirmed',priority:'Normal',message:'Hi, my backpack was supposed to arrive yesterday, but it still hasn’t turned up. The tracking hasn’t really changed. Could you check where it is and when I can expect it?\n\nThanks,\nMaya',events:[['Processing delay','Bangkok sorting hub · 13 Sep, 9:10 AM'],['Arrived at sorting hub','Bangkok · 11 Sep, 8:24 AM'],['Collected by carrier','Northline warehouse · 9 Sep, 3:05 PM']],recommendation:'Check the delay with the carrier',reason:'The promised date has passed and the carrier has not provided a new estimate. Open an inquiry before promising a delivery date.',action:'Start carrier inquiry',actionResult:'Carrier inquiry recorded',policy:'Sample store policy: if the promised delivery date has passed and no new estimate exists, open a carrier inquiry. Do not promise a new date until the carrier confirms it.'},
  {id:'1041',name:'Oliver Brooks',initials:'OB',email:'oliver.brooks@example.com',subject:'It says delivered. Nothing here.',time:'9:31 AM',kind:'missing',label:'Not received',tone:'red',order:'NL-2079',product:'Weekend duffel',variant:'Charcoal / 1 item',total:'฿2,490.00',destination:'Bangkok, TH',ordered:'7 Sep 2026',promised:'12 Sep 2026',tracking:'PP-TH-082079',shipment:'Marked as delivered',shipmentNote:'Customer reports a missing parcel',progress:4,eta:'Delivered 12 Sep',priority:'High',message:'Hello, the tracking says my bag was delivered yesterday afternoon, but I can’t find it. I checked with reception and they don’t have it either. Can you help me find out where it was left?',events:[['Marked as delivered','Bangkok · 12 Sep, 2:18 PM'],['Out for delivery','Bangkok local depot · 12 Sep, 8:10 AM'],['Arrived at local depot','Bangkok · 11 Sep, 6:52 PM']],recommendation:'Request proof of delivery',reason:'The delivered scan conflicts with the customer’s report. Request the delivery photo or signature to establish where the parcel was left.',action:'Request delivery proof',actionResult:'Proof-of-delivery request recorded',policy:'Sample store policy: for a delivered-but-not-received claim, request delivery proof and investigate before deciding on a replacement or refund.'},
  {id:'1040',name:'Aisha Khan',initials:'AK',email:'aisha.khan@example.com',subject:'I missed the delivery driver',time:'9:18 AM',kind:'missed',label:'Attempt failed',tone:'orange',order:'NL-2071',product:'Travel organizer set',variant:'Sand / 1 set',total:'฿890.00',destination:'Nonthaburi, TH',ordered:'8 Sep 2026',promised:'13 Sep 2026',tracking:'PP-TH-082071',shipment:'Delivery attempted',shipmentNote:'Recipient was unavailable',progress:3,eta:'Awaiting preference',priority:'Normal',message:'Hi there, I was at work when the driver came this morning. Can they try again tomorrow, or could I collect my order somewhere instead?',events:[['Recipient unavailable','Nonthaburi · 13 Sep, 8:50 AM'],['Out for delivery','Nonthaburi local depot · 13 Sep, 7:20 AM'],['Arrived at local depot','Nonthaburi · 12 Sep, 5:15 PM']],recommendation:'Confirm a preferred delivery option',reason:'Ask whether tomorrow’s redelivery is the customer’s preference or whether they want collection details. The carrier still needs to confirm availability.',action:null,policy:'Sample store policy: collect the customer’s redelivery or collection preference, then confirm the available option with the carrier. Do not present an unconfirmed slot as booked.'},
  {id:'1039',name:'Noah Williams',initials:'NW',email:'noah.williams@example.com',subject:'Can I update my apartment number?',time:'8:56 AM',kind:'address',label:'Address issue',tone:'blue',order:'NL-2068',product:'Daily crossbody bag',variant:'Black / 1 item',total:'฿1,290.00',destination:'Bangkok, TH',ordered:'9 Sep 2026',promised:'14 Sep 2026',tracking:'PP-TH-082068',shipment:'Address clarification needed',shipmentNote:'Apartment number is missing',progress:2,eta:'On hold',priority:'Normal',message:'I just noticed I forgot to put my apartment number on the order. I’m in unit 7B. The rest of the address is correct. Is it possible to add it before delivery?',events:[['Incomplete delivery address','Bangkok sorting hub · 13 Sep, 8:20 AM'],['Shipment received at hub','Bangkok · 12 Sep, 4:45 PM'],['Collected by carrier','Northline warehouse · 11 Sep, 2:30 PM']],recommendation:'Request the address correction',reason:'The customer provided unit 7B. Submit the correction for carrier review; the parcel stays on hold until the carrier accepts the change.',action:'Request address correction',actionResult:'Unit 7B correction request recorded',policy:'Sample store policy: a correction to an in-transit order must be confirmed by the carrier. Record the requested correction without marking the delivery address as successfully changed.'},
  {id:'1038',name:'Sofia Reyes',initials:'SR',email:'sofia.reyes@example.com',subject:'Any update on my order?',time:'8:40 AM',kind:'transit',label:'In transit',tone:'blue',order:'NL-2063',product:'Insulated bottle',variant:'Ocean / 1 item',total:'฿690.00',destination:'Phuket, TH',ordered:'10 Sep 2026',promised:'15 Sep 2026',tracking:'PP-TH-082063',shipment:'On the way',shipmentNote:'Moving through the carrier network',progress:2,eta:'15 Sep 2026',priority:'Normal',message:'Hey, I’m heading away next week and just wanted to check how my order is coming along. Do you know when it should arrive? Thanks!',events:[['Departed sorting hub','Bangkok · 13 Sep, 7:40 AM'],['Arrived at sorting hub','Bangkok · 12 Sep, 8:00 PM'],['Collected by carrier','Northline warehouse · 12 Sep, 1:10 PM']],recommendation:'Share the current delivery estimate',reason:'Tracking shows normal movement and the order is still within its promised delivery window. Share the estimate and explain it is not guaranteed.',action:null,policy:'Sample store policy: when tracking is moving within the delivery window, share the carrier’s current estimate. Treat the estimate as provisional, not a delivery guarantee.'},
  {id:'1037',name:'Ethan Park',initials:'EP',email:'ethan.park@example.com',subject:'No tracking updates for a week',time:'8:22 AM',kind:'lost',label:'No movement',tone:'red',order:'NL-2048',product:'Weekender kit',variant:'Stone / 2 items',total:'฿3,190.00',destination:'Chiang Rai, TH',ordered:'3 Sep 2026',promised:'9 Sep 2026',tracking:'PP-TH-082048',shipment:'Shipment may be lost',shipmentNote:'No tracking movement for 7 days',progress:2,eta:'Not confirmed',priority:'High',message:'My order hasn’t moved since last Sunday and it was supposed to be here on the 9th. I’ve been waiting a while now. Can you please look into this and let me know what can be done?',events:[['Last scan: departed hub','Bangkok · 6 Sep, 8:15 AM'],['Arrived at sorting hub','Bangkok · 5 Sep, 9:20 AM'],['Collected by carrier','Northline warehouse · 4 Sep, 11:35 AM']],recommendation:'Escalate a possible lost shipment',reason:'The delivery window has passed and there has been no scan for seven days. Request a shipment investigation. A refund or replacement needs review.',action:'Escalate for investigation',actionResult:'Lost-shipment investigation recorded',policy:'Sample store policy: seven days without a scan and a missed promised date qualifies for a shipment investigation. A support lead reviews refund or replacement eligibility; no automatic refund is issued.'}
];
let tickets,selectedId,filter,toastTimer;
const $=s=>document.querySelector(s);
const icon=name=>`<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const current=()=>tickets.find(t=>t.id===selectedId);
const statusName=t=>({open:'Open',waiting:'Waiting on customer',escalated:'Waiting on carrier',resolved:'Resolved'}[t.status]);
const statusTone=t=>({open:'blue',waiting:'blue',escalated:'orange',resolved:'green'}[t.status]);
function reset(){tickets=structuredClone(SEED).map(t=>({...t,status:'open',draft:'',messages:[],actioned:false,log:[]}));selectedId=tickets[0].id;filter='active';render();}
function notify(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>{$('#toast').hidden=true},4500);}
function visibleTickets(){return tickets.filter(t=>filter==='resolved'?t.status==='resolved':t.status!=='resolved');}
function renderQueue(){
  const resolved=tickets.filter(t=>t.status==='resolved').length;
  $('#active-count').textContent=tickets.length-resolved;$('#resolved-count').textContent=resolved;$('#resolved-progress').textContent=`${resolved} of ${tickets.length} tickets resolved`;
  $('#active-filter').classList.toggle('active',filter==='active');$('#resolved-filter').classList.toggle('active',filter==='resolved');
  $('#active-filter').setAttribute('aria-pressed',String(filter==='active'));$('#resolved-filter').setAttribute('aria-pressed',String(filter==='resolved'));
  $('#queue-label').textContent=filter==='resolved'?'RESOLVED TICKETS':'ACTIVE TICKETS';
  $('#ticket-list').innerHTML=visibleTickets().map(t=>`<button class="ticket-item ${t.id===selectedId?'selected':''}" data-ticket="${t.id}" aria-pressed="${t.id===selectedId}" aria-label="${esc(t.name)}, ${esc(t.subject)}, ${esc(statusName(t))}"><div class="ticket-name-row">${t.status==='open'?'<span class="unread-dot"></span>':''}${esc(t.name)}<span class="ticket-time">${esc(t.time)}</span></div><p class="ticket-subject">${esc(t.subject)}</p><div class="ticket-bottom"><span class="chip ${t.status==='open'?t.tone:statusTone(t)}">${t.status==='resolved'?icon('check'):''}${esc(t.status==='open'?t.label:statusName(t))}</span><span class="ticket-number">#${t.id}</span></div></button>`).join('')||`<div class="empty-state">${icon('inbox')}<strong>${filter==='resolved'?'No resolved tickets yet':'You’re all caught up'}</strong>${filter==='resolved'?'Resolve a ticket and it will appear here.':'All six delivery tickets are resolved.'}</div>`;
}
function renderWorkspace(){
  const t=current();
  if(!t){$('#ticket-workspace').innerHTML=`<div class="empty-state">${icon('check')}<strong>${filter==='resolved'?'Your resolved tickets will appear here.':'Inbox cleared.'}</strong>${filter==='resolved'?'Switch to Inbox to open a sample ticket.':'You can review resolved tickets or reset the demo.'}</div>`;return;}
  $('#ticket-workspace').innerHTML=`
  <div class="ticket-header"><div><div class="ticket-breadcrumb">Delivery inbox ${icon('chevron')}<span>Ticket #${t.id}</span></div><h2>${esc(t.subject)}</h2><div class="ticket-meta"><span class="chip ${statusTone(t)}">${statusName(t)}</span><span class="meta-divider"></span><span>${esc(t.name)}</span><span class="meta-divider"></span><span>Email</span>${t.priority==='High'?'<span class="chip red">High priority</span>':''}</div></div><button class="button secondary" id="resolve-button" aria-label="${t.status==='resolved'?'Reopen ticket':'Mark ticket as resolved'}" title="${t.status==='resolved'?'Reopen ticket':'Mark ticket as resolved'}">${icon(t.status==='resolved'?'refresh':'check')}<span>${t.status==='resolved'?'Reopen ticket':'Resolve ticket'}</span></button></div>
  <div class="content-grid"><div class="main-column">
    <section class="panel"><div class="panel-heading"><h3 class="panel-title">${icon('mail')}Conversation</h3><span>13 SEP 2026</span></div><div class="conversation" id="conversation"><div class="message"><div class="message-person"><span class="avatar">${t.initials}</span><div><strong>${esc(t.name)}</strong><small>${esc(t.email)}</small></div><span class="message-date">${t.time}</span></div><p class="message-body">${esc(t.message)}</p></div>${t.messages.map(m=>`<div class="message message-sent"><div class="message-person"><span class="avatar">D</span><div><strong>You <span class="message-sent-label">DEMO REPLY</span></strong><small>To ${esc(t.name)}</small></div><span class="message-date">This session</span></div><p class="message-body">${esc(m)}</p></div>`).join('')}${t.log.map(l=>`<div class="event-note">${icon('info')}<span>${esc(l)}</span></div>`).join('')}</div></section>
    ${t.status==='resolved'?`<div class="resolved-notice">${icon('check')}This ticket is resolved. Reopen it to continue the conversation.</div>`:`
    <section class="recommendation"><div class="recommendation-label">${icon('note')}RECOMMENDED NEXT STEP</div><h3>${esc(t.recommendation)}</h3><p>${esc(t.reason)}</p>${t.actioned?`<div class="recommendation-actioned">${icon('check')}${esc(t.actionResult)} · demo</div>`:t.action?`<button class="button soft small" id="action-button">${esc(t.action)}${icon('arrow')}</button>`:''}<details class="policy-details"><summary>Why this action?</summary><p>${esc(t.policy)}</p></details></section>
    <section class="panel composer"><div class="composer-heading"><h3 class="panel-title">${icon('note')}Your reply</h3><button class="draft-button" id="draft-button" ${t.draft.trim()?'disabled':''}>${icon('note')}Use suggested reply</button></div><div class="recipient-line"><span>To</span><strong>${esc(t.email)}</strong></div><textarea id="reply-text" aria-label="Reply to ${esc(t.name)}" maxlength="10000" placeholder="Write a reply, or use the suggested reply to get started…">${esc(t.draft)}</textarea><div class="composer-footer"><span class="draft-hint">${icon('info')}Review the details before sending.</span><button class="button primary" id="send-button" ${!t.draft.trim()?'disabled':''}>Send demo reply${icon('send')}</button></div></section>`}
    </div><aside class="context-column" aria-label="Order and shipment details"><h3 class="context-heading">ORDER CONTEXT <span>Matched to this ticket</span></h3><section class="panel shipment"><div class="shipment-top"><div class="shipment-label"><strong>${icon('box')} &nbsp;#${t.order}</strong><span>ParcelPost</span></div><div class="shipment-status"><div class="shipment-icon ${t.kind==='transit'?'green':''}">${icon(t.kind==='transit'?'truck':'box')}</div><div><h3>${esc(t.shipment)}</h3><p>${esc(t.shipmentNote)}</p></div></div><div class="shipment-progress" role="img" aria-label="${t.progress} of 4 shipping stages">${Array.from({length:4},(_,i)=>`<span class="${i<t.progress?'complete':''} ${t.kind==='transit'&&i<t.progress?'done':''}"></span>`).join('')}</div><div class="progress-labels"><span>Confirmed</span><span>Delivered</span></div></div><dl class="shipment-facts"><dt>${t.kind==='missing'?'Carrier delivery scan':'Expected delivery'}</dt><dd class="eta">${esc(t.eta)}</dd><dt>Originally promised</dt><dd>${esc(t.promised)}</dd><dt>Tracking number</dt><dd>${esc(t.tracking)}</dd></dl><div class="tracking-section"><h4 class="tracking-heading">LATEST TRACKING ACTIVITY</h4><ol class="timeline">${t.events.map(e=>`<li><strong>${esc(e[0])}</strong><p>${esc(e[1])}</p></li>`).join('')}</ol></div></section><section class="panel"><div class="panel-heading"><h3 class="panel-title">Order details</h3><span>PAID</span></div><div class="order-content"><div class="order-product"><div class="product-icon">${icon('box')}</div><div><strong>${esc(t.product)}</strong><span>${esc(t.variant)}</span></div></div><dl class="order-facts"><dt>Order value</dt><dd>${esc(t.total)}</dd><dt>Placed on</dt><dd>${esc(t.ordered)}</dd><dt>Delivering to</dt><dd>${esc(t.destination)}</dd></dl></div></section><span class="context-footnote">${icon('info')}Sample snapshot · 13 Sep 2026, 10:00 AM</span></aside></div>`;
}
function render(){renderQueue();renderWorkspace();}
function selectTicket(id){if(!tickets.some(t=>t.id===id))throw new Error('Unknown ticket ID.');selectedId=id;const t=current();filter=t.status==='resolved'?'resolved':'active';render();document.querySelector('[data-ticket="'+id+'"]')?.focus();return{id:t.id,status:t.status};}
function changeFilter(value){filter=value;if(!visibleTickets().some(t=>t.id===selectedId))selectedId=visibleTickets()[0]?.id||null;render();document.getElementById(value==='resolved'?'resolved-filter':'active-filter').focus();}
function draftFor(t){
  const first=t.name.split(' ')[0];
  const intros={delay:`I’m sorry your order ${t.order} hasn’t arrived by the promised date. The latest scan shows a processing delay at the Bangkok sorting hub. The carrier hasn’t confirmed a new delivery estimate yet.`,missing:`I’m sorry you haven’t received order ${t.order}. Tracking shows a delivery scan on 12 September at 2:18 PM, but I understand you’ve already checked with reception and the parcel is missing.`,missed:`The tracking for order ${t.order} shows that delivery was attempted this morning while you were unavailable. Would you prefer redelivery tomorrow, if the carrier can arrange it, or would you like me to check the collection options?`,address:`Thanks for the correction for order ${t.order}. I’ve noted that the apartment number should be 7B and that the rest of the address is correct. Tracking currently shows a hold for an incomplete address.`,transit:`Your order ${t.order} is on its way. The latest tracking scan shows it departed the Bangkok sorting hub this morning. The carrier’s current delivery estimate is 15 September. This is an estimate rather than a guaranteed arrival date.`,lost:`I’m sorry about the long wait for order ${t.order}. The latest scan is from 6 September, and the promised 9 September delivery date has passed. We need the carrier to investigate before we can confirm what happened.`};
  const after={delay:t.actioned?'I’ve opened a carrier inquiry in this demo. Once the carrier provides an update, we can share the revised estimate.':'The next step is to open a carrier inquiry and request an updated delivery estimate.',missing:t.actioned?'I’ve requested proof of delivery in this demo so we can check where the parcel was left. A replacement or refund will need to be reviewed once we have the findings.':'The next step is to request proof of delivery so we can check where the parcel was left before reviewing a replacement or refund.',missed:'Once you confirm your preference, we can check availability with the carrier. No new delivery or collection slot is booked yet.',address:t.actioned?'I’ve recorded a request to add unit 7B in this demo. The carrier still needs to confirm the change, so the delivery remains on hold for now.':'The next step is to request that the carrier add unit 7B. The carrier needs to accept the correction before we can confirm it has been updated.',transit:`Your tracking reference is ${t.tracking}. Please get back in touch if it hasn’t arrived by the estimated date, and we can check again.`,lost:t.actioned?'I’ve escalated this for a shipment investigation in this demo. The outcome will help our support lead review whether a replacement or refund is appropriate.':'The next step is to escalate this for a shipment investigation. Our support lead can then review whether a replacement or refund is appropriate.'};
  return `Hi ${first},\n\n${intros[t.kind]}\n\n${after[t.kind]}\n\nBest,\nNorthline Support`;
}
function prepareDraft(){const t=current();if(!t||t.status==='resolved')throw new Error('Select an active ticket first.');if(t.draft.trim())throw new Error('A draft already exists. Edit it or clear it before preparing another.');t.draft=draftFor(t);renderWorkspace();$('#reply-text').focus();return{ticketId:t.id,draft:t.draft};}
function recordAction(){const t=current();if(!t||!t.action||t.status==='resolved')throw new Error('No available carrier action for this ticket.');if(t.actioned)throw new Error('This action is already recorded.');const isSuggested=t.draft===draftFor(t);t.actioned=true;t.status='escalated';if(isSuggested)t.draft=draftFor(t);t.log.push(`${t.actionResult} — simulated. No request was sent to a carrier.`);render();$('#draft-button')?.focus();notify('Action recorded in the demo. No carrier was contacted.');return{ticketId:t.id,status:t.status,simulated:true};}
function sendReply(){const t=current();if(!t||t.status==='resolved'||!t.draft.trim())throw new Error('An active ticket and a nonempty reply are required.');t.messages.push(t.draft.trim());t.draft='';t.status=t.actioned?'escalated':'waiting';render();$('#draft-button')?.focus();const conversation=$('#conversation');if(conversation)conversation.scrollTop=conversation.scrollHeight;notify('Demo reply added to the conversation. No email was sent.');return{ticketId:t.id,status:t.status,messageCount:t.messages.length,simulated:true};}
function toggleResolved(){const t=current();if(!t)throw new Error('Select a ticket first.');const resolved=t.status==='resolved';if(resolved){t.status=t.previousStatus||'open';filter='active';t.log.push('Ticket reopened in this demo.');}else{t.previousStatus=t.status;t.status='resolved';t.log.push('Ticket marked as resolved in this demo.');filter='resolved';}render();$('#resolve-button')?.focus();notify(resolved?'Ticket reopened. Your conversation is preserved.':'Ticket resolved. You can reopen it from Resolved.');return{ticketId:t.id,status:t.status};}
document.addEventListener('click',event=>{
  const target=event.target.closest('button');if(!target)return;
  if(target.dataset.ticket){selectTicket(target.dataset.ticket);return;}
  if(target.dataset.close){document.getElementById(target.dataset.close).close();return;}
  const actions={'active-filter':()=>changeFilter('active'),'resolved-filter':()=>changeFilter('resolved'),'about-button':()=>$('#about-dialog').showModal(),'reset-button':()=>$('#reset-dialog').showModal(),'confirm-reset':()=>{$('#reset-dialog').close();reset();notify('Demo reset. All six sample tickets are ready.');},'draft-button':prepareDraft,'action-button':recordAction,'send-button':sendReply,'resolve-button':toggleResolved};
  if(actions[target.id]){try{actions[target.id]();}catch(error){notify(error.message);}}
});
document.addEventListener('input',event=>{if(event.target.id!=='reply-text')return;const t=current();if(!t)return;t.draft=event.target.value;$('#send-button').disabled=!t.draft.trim();$('#draft-button').disabled=!!t.draft.trim();});
reset();

// Optional WebMCP tools use the same state and actions as the visible interface.
const modelContext=document.modelContext;
if(modelContext?.registerTool){
  const lifecycle=new AbortController();
  const toolDefinitions=[
    {name:'read_delivery_tickets',title:'Read delivery tickets',description:'Read all fictional delivery tickets and the selected ticket. Does not change state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Pass an empty object.');return{selectedId,tickets:tickets.map(t=>({id:t.id,customer:t.name,subject:t.subject,status:t.status,shipment:t.shipment,eta:t.eta,actioned:t.actioned,draft:t.draft,messageCount:t.messages.length}))};}},
    {name:'open_delivery_ticket',title:'Open a delivery ticket',description:'Select an existing fictional ticket and show its conversation, shipment facts, and next step.',inputSchema:{type:'object',properties:{ticketId:{type:'string'}},required:['ticketId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.ticketId!=='string'||Object.keys(input).some(k=>k!=='ticketId'))throw new Error('Provide only a string ticketId.');return selectTicket(input.ticketId);}},
    {name:'prepare_delivery_reply',title:'Prepare a delivery reply',description:'Stage a rule-based draft for the currently selected active ticket. Requires an empty draft. Does not send a reply or contact anyone.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Pass an empty object.');return prepareDraft();}}
  ];
  for(const tool of toolDefinitions){try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
